#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
$HOME/.config/polybar/launch.sh &
<path to your xborders> -c ~/.config/xborders/config.json &
feh --bg-fill ~/.wallpapers/tanjiro-nezuko-wallpaper.png

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
